#!/bin/sh

prefix=/usr/local/c-icap

PKGLIBDIR=/usr/local/c-icap/lib/c_icap/
LIBDIR=/usr/local/c-icap/lib/
CONFIGDIR=/usr/local/c-icap/etc/
DATADIR=/usr/local/c-icap/share/c_icap/
#LOGDIR=
SOCKDIR=/var/run/c-icap

INCDIR=/usr/local/c-icap/include
INCDIR2=/usr/local/c-icap/include/c_icap

VERSION=0.5.6
CICAPCFLAGS="-D_REENTRANT -g -O2 -Wall -D_FILE_OFFSET_BITS=64"
CICAPLDFLAGS=
CICAPLIBS=
CFLAGS="-DCI_BUILD_MODULE -D_REENTRANT -g -O2 -Wall -D_FILE_OFFSET_BITS=64"
LIBS=
LDFLAGS=""


usage()
{
   cat <<EOTXT
Usage: c-icap-config [OPTIONS]

Where OPTION one of the following:
   --prefix             print c-icap instalation base directory
   --cflags		print preprocessor and compiler flags
   --libs		print linker flags
   --datarootdir	print the c-icap data directory
   --configdir		print the c-icap configuration directory
   --modulesdir		print the c-icap modules/plugins directory
   --version		print the c-icap server version
   --config		print the c-icap server compile configuration
EOTXT
}


case $1 in
    '--prefix')
        echo $prefix;
        ;;
    '--cflags')
        echo $CFLAGS" -I"$INCDIR" -I"$INCDIR2;
        ;;
    '--libs')
       echo $LIBS;
       ;;
    '--datarootdir')
       echo $DATADIR;
       ;;
    '--configdir')
       echo $CONFIGDIR;
       ;;
    '--modulesdir')
       echo $PKGLIBDIR;
       ;;
    '--version')
       echo $VERSION;
       ;;
    '--config')
        echo "c-icap configuration";
	echo "c-icap version: "$VERSION;
        echo "c-icap installation prefix: "$prefix
	echo "c-icap configuration directory: "$CONFIGDIR;
	echo "c-icap modules/plugins directory: "$PKGLIBDIR;
	echo "c-icap shared data directory: "$DATADIR;
	echo ;
        echo "c-icap cflags for modules: "$CFLAGS;
        echo "c-icap libs for modules: "$LIBS;
       ;;
    *)
        usage
esac;
