#!/bin/sh

prefix=/usr/local/c-icap

PKGLIBDIR=/usr/local/c-icap/lib/c_icap/
LIBDIR=/usr/local/c-icap/lib/
CONFIGDIR=/usr/local/c-icap/etc/
DATADIR=/usr/local/c-icap/share/c_icap/
#LOGDIR=
SOCKDIR=/var/run/c-icap

INCDIR=/usr/local/c-icap/include
INCDIR2=/usr/local/c-icap/include/c_icap

VERSION=0.5.6

CFLAGS="-D_REENTRANT -g -O2 -Wall -D_FILE_OFFSET_BITS=64"
LIBS="-L$LIBDIR -licapapi "
LDFLAGS=""


usage()
{
   cat <<EOTXT
Usage: c-icap-libicapapi-config [OPTIONS]

Where OPTION one of the following:
   --cflags		print preprocessor and compiler flags
   --libs		print linker flags
   --version		print the c-icap library  version
EOTXT
}


case $1 in
    '--cflags')
        echo $CFLAGS" -I"$INCDIR" -I"$INCDIR2;
        ;;
    '--libs')
       echo $LIBS;
       ;;
    '--version')
       echo $VERSION;
       ;;
    *)
        usage
esac;
